name: Document Conversion

on: [push]

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: maxheld83/pandoc@master
        with:
          args: --standalone --output=index.html $GITHUB_WORKSPACE/README.md
